logging:
  level:
    org:
      springframework: info

server:
  error:
    include-message: always

spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/petstore
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      enabled: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:/db.migration,classpath:/db.datainit
    url: jdbc:mysql://localhost:3306/petstore?createDatabaseIfNotExist=true
    user: root
    password: root