name: Java CI/CD
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build with Gradle
        run: gradle clean build
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}
      - name: Build and Deploy Docker Image
        run: |
          docker build . --file Dockerfile --tag ${{ env.DOCKER_USERNAME }}/petstore
          docker push ${{ env.DOCKER_USERNAME }}/petstore
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Copy docker-compose.yml to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ec2-23-21-28-163.compute-1.amazonaws.com
          username: ec2-user
          key: ${{ env.SSH_PRIVATE_KEY }}
          source: ./docker-compose.yml
          target: ~/docker/
      - name: SSH to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ec2-23-21-28-163.compute-1.amazonaws.com
          username: ec2-user
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd ~/docker
            docker-compose down
            docker-compose pull
            docker-compose up -d